server:
  port: 8087

spring:
  application:
        name: RATINGSERVICE
  data:
    mongodb:
        uri: mongodb+srv://ashpatil4040:Anikash%4023@cluster0.kke9j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        database: microservices
  

  config:
      import: configserver:http://localhost:8089

# eureka:
#   instance:
#     prefer-ip-address: true

#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka             